/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testlaythongtinmay;

import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.net.UnknownHostException;
import com.sun.management.OperatingSystemMXBean;
import java.lang.management.ManagementFactory;
import java.util.List;
import javax.swing.JOptionPane;

import oshi.SystemInfo;
import oshi.hardware.CentralProcessor;
import oshi.hardware.GlobalMemory;
import oshi.hardware.HWDiskStore;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.hardware.PhysicalMemory;
import oshi.software.os.OperatingSystem;
import oshi.software.os.FileSystem;
import oshi.software.os.OSFileStore;
/**
 *
 * @author admin
 */
public class formDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form formDangNhap
     */
    public formDangNhap() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_dn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MSGV:");

        jLabel2.setText("Mật khẩu:");

        btn_dn.setText("Đăng nhập");
        btn_dn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Đăng nhập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_username)
                            .addComponent(txt_pass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(btn_dn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 293, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(62, 62, 62)
                .addComponent(btn_dn)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dnActionPerformed
        // TODO add your handling code here:
        String username = txt_username.getText();
        String password = txt_pass.getText();
        try
        {
            InetAddress localHost = InetAddress.getLocalHost();
            String tenmay = localHost.getHostName();
            SystemInfo systemInfo = new SystemInfo();
            CentralProcessor cpu = systemInfo.getHardware().getProcessor();
            String tencpu = cpu.getProcessorIdentifier().getName();
            OperatingSystem hedieuhanh = systemInfo.getOperatingSystem();
            String os = hedieuhanh.getFamily();
            //Lay ram
            SystemInfo si = new SystemInfo();
            HardwareAbstractionLayer hal = si.getHardware();
            GlobalMemory memory = hal.getMemory();
            String serial1 = null, serial2 = null;
            int i = 0;
            for (PhysicalMemory pm : memory.getPhysicalMemory()) {
                if (i == 0) serial1 = pm.getSerialNumber();
                else if (i == 1) serial2 = pm.getSerialNumber();
                i++;
            }
            if (i == 1) serial2 = null;
            String ram1 = (serial1 != null ? serial1 : "NULL");
            String ram2 = (serial2 != null ? serial2 : "NULL");
            //Lấy rom
            List<HWDiskStore> disks = hal.getDiskStores();
            String serialRom1 = null, serialRom2 = null;
            int j = 0;
            for (HWDiskStore disk : disks) {
                if (j == 0) serialRom1 = disk.getSerial();
                else if (j == 1) serialRom2 = disk.getSerial();
                j++;
            }
            if (j == 1) serialRom2 = null;
            String rom1 = (serialRom1 != null ? serialRom1 : "NULL");
            String rom2 = (serialRom2 != null ? serialRom2 : "NULL");
            
            mycls cls = new mycls();
            username = cls.mahoa(username);
            username = username.replace("+", "%2B");
            password = cls.mahoa(password);
            password = password.replace("+", "%2B");
            tenmay = cls.mahoa(tenmay);
            tenmay = tenmay.replace("+", "%2B");
            tencpu = cls.mahoa(tencpu);
            tencpu = tencpu.replace("+", "%2B");
            os = cls.mahoa(os);
            os = os.replace("+", "%2B");
            ram1 = cls.mahoa(ram1);
            ram1 = ram1.replace("+", "%2B");
            ram2 = cls.mahoa(ram2);
            ram2 = ram2.replace("+", "%2B");
            rom1 = cls.mahoa(rom1);
            rom1 = rom1.replace("+", "%2B");
            rom2 = cls.mahoa(rom2);
            rom2 = rom2.replace("+", "%2B");
            
            String thamso = "username="+username+"&password="+password+"&ram1="+ram1+"&ram2="+ram2+"&rom1="+rom1+"&rom2="+rom2+"&tenmay="+tenmay+"&tencpu="+tencpu+"&os="+os+"";
            String url = Constants.API_LOGIN+thamso;

            
            JSONArray jarr = new JSONArray();
            jarr = cls.docapi(url);
            for(int it=0;it<cls.docapi(url).length();it++)
            {
                try {
                    JSONObject jon = jarr.getJSONObject(it);
                    String iduser = String.valueOf(jon.getInt("iduser")); 
                    int response = jon.getInt("Response");
                    int pq = jon.getInt("PQ");
                    String name = jon.getString("name");
                    if(response == 101 && pq == 1)
                    {
                        
                        formDangKy fm = new formDangKy(iduser,name);
                        fm.setVisible(true);
                        this.setVisible(false);
                        this.dispose();
                    }
                    else if(response == 102 && pq == 1)
                    {
                        String token = jon.getString("token");
                        long time = jon.getLong("time");
                        cls.ghifile(token,time);
                        
                        myform mf = new myform(iduser,name);
                        mf.setVisible(true);
                        this.setVisible(false);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            
        }catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_dnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
