/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testlaythongtinmay;

import java.io.File;
import java.net.InetAddress;
import java.net.UnknownHostException;
import com.sun.management.OperatingSystemMXBean;
import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import oshi.SystemInfo;
import oshi.hardware.CentralProcessor;
import oshi.software.os.OperatingSystem;
import oshi.software.os.FileSystem;
import oshi.software.os.OSFileStore;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.hardware.GlobalMemory;
import oshi.hardware.PhysicalMemory;
import oshi.hardware.HWDiskStore;
/**
 *
 * @author admin
 */
public class formDangKy extends javax.swing.JFrame {

    /**
     * Creates new form myform
     */
    public formDangKy(String id,String name) {
        initComponents();
        setLocationRelativeTo(null);
        txt_id.setText(id);
        txt_name.setText(name);
        setLocationRelativeTo(null);
        
    }
    private formDangKy() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_tenmay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_Ram1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Rom1 = new javax.swing.JTextField();
        txt_CPU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_OS = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Ram2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Rom2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Xem thông tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_tenmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenmayActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên máy");

        txt_Ram1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Ram1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ram1");

        jLabel3.setText("Rom1");

        txt_Rom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Rom1ActionPerformed(evt);
            }
        });

        jLabel4.setText("CPU");

        jLabel5.setText("Hệ Điều Hành");

        btn_Them.setText("Đăng ký");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        jLabel6.setText("Ram2");

        jLabel7.setText("Rom2");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Bạn phải đăng ký máy để thực hiện tiếp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Ram2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                    .addComponent(txt_Ram1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tenmay)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Rom2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                    .addComponent(txt_CPU, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_OS, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Rom1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(txt_name))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_tenmay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(txt_Ram1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Ram2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txt_Rom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txt_Rom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_OS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Lấy tên máy tính
            InetAddress localHost = InetAddress.getLocalHost();
            String computerName = localHost.getHostName();
            txt_tenmay.setText(computerName);
            //Lấy ram
            SystemInfo si = new SystemInfo();
            HardwareAbstractionLayer hal = si.getHardware();
            GlobalMemory memory = hal.getMemory();
            String serial1 = null, serial2 = null;
            int i = 0;
            for (PhysicalMemory pm : memory.getPhysicalMemory()) {
                if (i == 0) serial1 = pm.getSerialNumber();
                else if (i == 1) serial2 = pm.getSerialNumber();
                i++;
            }
            if (i == 1) serial2 = null;
            txt_Ram1.setText(serial1 != null ? serial1 : "NULL");
            txt_Ram2.setText(serial2 != null ? serial2 : "NULL");
            
            
            
//          Lấy thông tin ổ đĩa (ROM)
            List<HWDiskStore> disks = hal.getDiskStores();
            String serialRom1 = null, serialRom2 = null;
            int j = 0;
            for (HWDiskStore disk : disks) {
                if (j == 0) serialRom1 = disk.getSerial();
                else if (j == 1) serialRom2 = disk.getSerial();
                j++;
            }
            if (j == 1) serialRom2 = null;
            txt_Rom1.setText(serialRom1 != null ? serialRom1 : "NULL");
            txt_Rom2.setText(serialRom2 != null ? serialRom2 : "NULL");

            
            SystemInfo systemInfo = new SystemInfo();
            CentralProcessor processor = systemInfo.getHardware().getProcessor();
            txt_CPU.setText(processor.getProcessorIdentifier().getName());
            
            OperatingSystem os = systemInfo.getOperatingSystem();
            // Hiển thị tên hệ điều hành
            txt_OS.setText(os.getFamily());
            
 
        } catch (UnknownHostException e) {
            System.err.println("Không thể lấy tên máy: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_tenmayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenmayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenmayActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        try{
        String tenmay = txt_tenmay.getText();
        String ram1 = txt_Ram1.getText();
        String ram2 = txt_Ram2.getText();
        String rom1 = txt_Rom1.getText();
        String rom2 = txt_Rom2.getText();
        String cpu = txt_CPU.getText();
        String os = txt_OS.getText();
        String id = txt_id.getText();
        mycls cls = new mycls();
        
        tenmay = cls.mahoa(tenmay);
        tenmay = tenmay.replace("+", "%2B");
        ram1 = cls.mahoa(ram1);
        ram1 = ram1.replace("+", "%2B");
        ram2 = cls.mahoa(ram2);
        ram2 = ram2.replace("+", "%2B");
        rom1 = cls.mahoa(rom1);
        rom1 = rom1.replace("+", "%2B");
        rom2 = cls.mahoa(rom2);
        rom2 = rom2.replace("+", "%2B");
        cpu = cls.mahoa(cpu);
        cpu = cpu.replace("+", "%2B");
        os = cls.mahoa(os);
        os = os.replace("+", "%2B");
        id = cls.mahoa(id);
        id = id.replace("+", "%2B");

        String thamso = "tenmay="+tenmay+"&ram1="+ram1+"&ram2="+ram2+"&rom1="+rom1+"&rom2="+rom2+"&tencpu="+cpu+"&os="+os+"&iduser="+id+"";
        String url = Constants.API_REGISTER + thamso;
        cls.geturl(url);
        JOptionPane.showMessageDialog(this, "Đăng ký thành công.");
        String id1 = cls.giaima(id);
        String name = txt_name.getText();
        myform fm = new myform(id1,name);
        fm.setVisible(true);
        this.setVisible(false);
        this.dispose();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void txt_Ram1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Ram1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Ram1ActionPerformed

    private void txt_Rom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Rom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Rom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_CPU;
    private javax.swing.JTextField txt_OS;
    private javax.swing.JTextField txt_Ram1;
    private javax.swing.JTextField txt_Ram2;
    private javax.swing.JTextField txt_Rom1;
    private javax.swing.JTextField txt_Rom2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_tenmay;
    // End of variables declaration//GEN-END:variables
}
