/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testlaythongtinmay;

import java.awt.Desktop;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.json.JSONArray;
import org.json.JSONObject;
/**
 *
 * @author admin
 */
public class myform extends javax.swing.JFrame {


    /**
     * Creates new form myform
     */
    public myform(String id, String name) {
        initComponents();
        customTableUI();
        setLocationRelativeTo(null);
//        this.pack();
        txt_id.setText(id);
        txt_name.setText(name);
        loaddetai();
    }

    private myform() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    private void customTableUI() {
    tbl_detai.setRowHeight(30);
    tbl_sinhvien.setRowHeight(30);
    
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    centerRenderer.setVerticalAlignment(SwingConstants.CENTER); 
    // Áp dụng cho tất cả các cột
    TableColumnModel columnModel = tbl_detai.getColumnModel();
    for (int i = 0; i < columnModel.getColumnCount(); i++) {
    columnModel.getColumn(i).setCellRenderer(centerRenderer);
    }
    TableColumnModel columnModel1 = tbl_sinhvien.getColumnModel();
    for (int i = 0; i < columnModel1.getColumnCount(); i++) {
    columnModel1.getColumn(i).setCellRenderer(centerRenderer);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        txt_iddetai = new javax.swing.JTextField();
        txt_idnhom = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_detai = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sinhvien = new javax.swing.JTable();
        btn_luu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_id.setUI(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("XIN CHÀO GIẢNG VIÊN ");

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txt_iddetai.setEditable(false);
        txt_iddetai.setUI(null);

        txt_idnhom.setUI(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_iddetai, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_idnhom, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_iddetai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idnhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_detai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_detai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_detai);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_sinhvien);

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)
            .addComponent(btn_luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void tbl_detaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detaiMouseClicked
        // TODO add your handling code here:
        int chon = tbl_detai.getSelectedRow();
        txt_iddetai.setText(tbl_detai.getValueAt(chon, 0).toString());
        txt_idnhom.setText(tbl_detai.getValueAt(chon, 3).toString());
        String id =  tbl_detai.getValueAt(chon, 0).toString();
        String idnhom = tbl_detai.getValueAt(chon, 3).toString();
        loadsinhvien(id,idnhom);
    }//GEN-LAST:event_tbl_detaiMouseClicked

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (tbl_sinhvien.isEditing()) {
            tbl_sinhvien.getCellEditor().stopCellEditing();
            }
        try {
            for(int i = 0;i<tbl_sinhvien.getRowCount();i++)
            {
                String idsv = (String) tbl_sinhvien.getValueAt(i, 0);
                String masv = (String) tbl_sinhvien.getValueAt(i, 1);
                String lop = (String) tbl_sinhvien.getValueAt(i, 4);
                String diem = String.valueOf(tbl_sinhvien.getValueAt(i, 5));
                
                
                String thamso = "diem="+diem+"&iduser="+idsv+"&MaSV="+masv+"&Lop="+lop+"";
                String url = Constants.API_NHAP_DIEM+thamso;
                mycls cls = new mycls();
                cls.geturl(url);
                
            }
            
            JOptionPane.showMessageDialog(null, "Lưu thành công");
            String iddetai = txt_iddetai.getText();
            String idnhom = txt_idnhom.getText();
            loadsinhvien(iddetai,idnhom);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lưu thất bại");
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void loaddetai()
    {
        mycls cls = new mycls();
        try
        {
            JSONArray jarr = new JSONArray();
            String id = txt_id.getText();
            String thamso = "id="+id+"";
            String url = Constants.API_XEM_DETAI+thamso;
            jarr = cls.docapi(url);
            Vector<Vector<String>> datalist = new Vector<>();
            for(int i=0; i<cls.docapi(url).length(); i++)
            {
                JSONObject job = jarr.getJSONObject(i);
                Vector<String> data = new Vector<>();
                data.add(job.getString("IDDeTai"));
                data.add(job.getString("TenDeTai"));
                data.add(job.getString("TrangThaiDeTai"));
                data.add(job.getString("idnhom"));
                datalist.add(data);
                
            }
            Vector<String> column = new Vector<>();
            column.add("ID");
            column.add("Tên Đề tài");
            column.add("Trạng thái");
            column.add("Nhóm");
            DefaultTableModel model = new DefaultTableModel(datalist, column) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_detai.setModel(model);
        customTableUI();

        }catch (Exception e)
        {
        
        }
    }
    private void loadsinhvien(String id, String idnhom)
    {
        mycls cls = new mycls();
        try
        {
            JSONArray jarr = new JSONArray();
//            String id = txt_iddetai.getText();
//            String idnhom = txt_idnhom.getText();
            String thamso = "iddetai="+id+"&idnhom="+idnhom+"";
            String url = Constants.API_XEM_DSSV+thamso;
            jarr = cls.docapi(url);
            Vector<Vector<String>> datalist = new Vector<>();
            for(int i=0; i<cls.docapi(url).length(); i++)
            {
                JSONObject job = jarr.getJSONObject(i);
                Vector<String> data = new Vector<>();
                data.add(job.getString("iduser"));
                data.add(job.getString("MaSV"));
                data.add(job.getString("HoDem"));
                data.add(job.getString("Ten"));
                data.add(job.getString("Lop"));
                data.add(job.getString("Diem"));  
                datalist.add(data);
                
            }
            Vector<String> column = new Vector<>();
            column.add("ID");
            column.add("Mã Sinh viên");
            column.add("Họ Đệm");
            column.add("Tên");
            column.add("Lớp");
            column.add("Điểm");
            DefaultTableModel model = new DefaultTableModel(datalist,column){
            @Override
            public boolean isCellEditable(int row, int column) {
                    return column != 0 && column != 1 && column != 2 && column != 3 && column != 4;
            }
            };
            tbl_sinhvien.setModel(model);
            customTableUI();

        }catch (Exception e)
        {
        
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_detai;
    private javax.swing.JTable tbl_sinhvien;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_iddetai;
    private javax.swing.JTextField txt_idnhom;
    private javax.swing.JLabel txt_name;
    // End of variables declaration//GEN-END:variables
}
